# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs

language: node_js

node_js:
  - 'node'
  - 'lts/*'

cache:
  directories:
    - 'node_modules'

before_script:
  - npm install

script:
  - npm lint
  - npm test

notifications:
  email: false
